### ISSUE TITLE
samtools view arguments in alignReads.sh/detectAllelicConcatenated function

### ISSUE THREAD

**Issue by michael-kotliar** [julienrichardalbert/MEA#7]
I assume the following line
```
$MEA_BIN_SAMTOOLS view -bt $PARAM_REFFASTA "$PARAM_OUT_PREFIX".sam > "$PARAM_OUT_PREFIX".unsorted.bam
```
should be updated to
```
$MEA_BIN_SAMTOOLS view -b "$PARAM_OUT_PREFIX".sam > "$PARAM_OUT_PREFIX".unsorted.bam
```
or at least to (in case of using STAR)
```
$MEA_BIN_SAMTOOLS view -bt `dirname $PARAM_REFFASTA`/chrNameLength.txt "$PARAM_OUT_PREFIX".sam > "$PARAM_OUT_PREFIX".unsorted.bam
```
in [alignReads.sh](https://github.com/julienrichardalbert/MEA/blob/c33981de99dfd20f76fd5cd904e2f630eef0f4ae/src/scripts/alignReads.sh#L222)

`PARAM_REFFASTA` points to the folder, not to the file `chrNameLength.txt`.

Samtools manual says 
```
The -t and -T options provide additional reference data. One of these two options is required when SAM input does not contain @SQ headers, and the -T option is required whenever writing CRAM output.
```
In case of STAR sam file already includes header, so we don't need `-t`. As for the other tools I didn't check.

**Comment by julienrichardalbert** [comment]
Good find. As you say, when using STAR, samtools must be using the sam header information because the code points to the folder, not chrNameLength.txt. 
This is one example of many redundancies in the code which ensures that each aligner (bowtie2, bwa, tophat2, STAR, bismark) is handled properly post-alignment. 
Of course, implementing these changes will improve the code and I will do so, thank you.
